### ISSUE TITLE
doc: Bash: also mention Git aliases

### ISSUE THREAD

**Issue by phil-blain** [felipec/git-completion#1]
Hi @felipec !

Thanks for putting this project together. I have two comments:

1. In the "Bash" page of the wiki, you mention how to make completion work for custom Bash aliases to Git commands or to the `git` command itself. It would be nice to mention that the trick for Bash aliases also works for Git aliases that shell out, like this:
```bash
$ git config --get alias.logv
!f() { git -C "$GIT_PREFIX" --work-tree=$PWD -c color.ui=always log --abbrev-commit --decorate --format=format:"%C(yellow)%h%C(reset) %C(normal)%s%C(reset) %C(dim white)%an%C(reset) %C(dim blue)(%ad)%C(reset) %C(auto)%d%C(reset) %C(green)%H%C(reset)" "$@" | git -p name-rev --stdin --name-only --tags; }; f
$ git logv --[TAB][TAB] # nothing happens
$ __git_complete 'git logv' _git_log
$ git logv --[TAB][TAB]
Display all 121 possibilities? (y or n)
--abbrev                   --dense                    --ignore-cr-at-eol         --no-max-parents           --reverse 
# ...
```

2. I noticed you recently created the wiki, and before that the doc was in the README. I think having the doc in the repo itself is more PR-friendly, since you can't do a PR to the wiki.

Cheers!

**Comment by felipec** [comment]
Thank you. I will think about moving that documentation depending now many requests for changes we get.

However, you don't need `__git_complete` for those kinds of aliases, the Git completion already detects them, you just need to add a little help:

    !f() { : git log ; ... ; } f

**Comment by phil-blain** [comment]
Ah ! I had not understood correctly the comment at the top of `git-completion.bash`. Thanks.

I thought it was about just adding `:`, but it's really about adding `: git <command> ; <whatever is your alias>`.

However, I noticed another shortcoming that could be worth documenting. If I have a "shortcut alias" like `git logo` for `git log --oneline --decorate` for example, completion works, but if I also have a "recursive" alias like `git loga` for `git logo --all`, then completion does not work for `git loga`. This is a case where using `__git_complete` would help for Git aliases.

**Comment by felipec** [comment]
Right. It shouldn't be too hard to fix. Have you contacted the mailing list about that issue?

**Comment by phil-blain** [comment]
Yes : https://lore.kernel.org/git/9717A684-9304-4A65-8566-19F946098455@gmail.com/

**Comment by felipec** [comment]
@phil-blain Cool. I replied to that and implemented that feature:

https://lore.kernel.org/git/20201109215248.461167-1-felipe.contreras@gmail.com/

**Comment by felipec** [comment]
I think the current version of the documentation in [Bash](https://github.com/felipec/git-completion/wiki/Bash) has all the relevant information, plus the fix for recursive aliases should deal with the rest of the issues.
