### ISSUE TITLE
Noob friendly instructions

### ISSUE THREAD

**Issue by Nick-Z0** [felipec/git-completion#4]
Hi, thanks for making this. I tried the official file for zsh and it didn't work, then I found this on your answer on SO.

It is not very clear to me how to install this. I made it work by just copying the `git-completion.zsh` and adding `fpath=(~/.zsh $fpath)` to the `.zshrsc`. Thus I am not able to use the configurations described in the wiki. 

It would be great if you could explain the installation a bit more, eg `make file` is not clear to me. Should I copy the folder, cd to the folder and then run `make file`?

Also in git-completion.zsh there are some additional instructions on installing this (from the official file) but I guess they are not applicable to your method. There is also stated that "You need git's bash completion script installed..." which is also not applicable since it shows a message that this method is deprecated. Maybe they could be removed to avoid confusion.

Cheers!

**Comment by felipec** [comment]
`make install` is a standard Linux command to install software. If you clone this repository, this command would copy the files for you. I've updated the instructions in the wiki: [Zsh installation](/felipec/git-completion/wiki/Zsh) to mention how you can copy the files manually.

Essentially you can rename `git-completion.zsh` to `_git`, and then place it under `~/.zsh` (or any directory in your `$fpath`).

That alone should work, but it would use your system's bash git completions, which do have some bugs. It's better if you copy `git-completion.bash` too, and use the standard location: `~/.local/share/bash-completion/completions/git`.

Hopefully that clear things up.
