### ISSUE TITLE
git subcommand flags not described

### ISSUE THREAD

**Issue by iloveitaly** [felipec/git-completion#8]
the subcommand descriptions aren't working for me:

<img width="597" alt="image" src="https://github.com/felipec/git-completion/assets/150855/0176c530-81f5-4a71-a1aa-6be76634ad6a">

Is this intended behavior?

**Comment by felipec** [comment]
Yes, the only descriptions provided are for git core options and common commands.

The idea was each command provided those descriptions so the completions would be generated automatically. Sadly that seems it's never going to happen.

We could manually add some descriptions for some commands, but it seems it's not very important for most people.
